package robot

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"alemonx/internal/pm2config"
)

const pm2SettingsPrefix = "// alemonx-pm2: "

var (
	pm2RegistrationNamePattern = regexp.MustCompile(`^[A-Za-z0-9._-]{1,80}$`)
	pm2EnvironmentNamePattern  = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)
	pm2MemoryPattern           = regexp.MustCompile(`^\d+(?:[KMG])?$`)
)

// PM2RegistrationSettings is the regular, intentionally small PM2 setup
// surface. The rest of ecosystem.config.cjs is generated by AlemonX.
type PM2RegistrationSettings struct {
	Name         string            `json:"name"`
	Script       string            `json:"script"`
	Autorestart  bool              `json:"autorestart"`
	MaxRestarts  int               `json:"maxRestarts"`
	MaxMemory    string            `json:"maxMemory,omitempty"`
	Env          map[string]string `json:"env"`
	Registered   bool              `json:"registered"`
	CustomConfig bool              `json:"customConfig"`
}

func defaultPM2RegistrationSettings(root string) PM2RegistrationSettings {
	defaults := pm2config.DefaultOptions(root)
	return PM2RegistrationSettings{
		Name:        defaults.Name,
		Script:      defaults.Script,
		Autorestart: defaults.Autorestart,
		MaxRestarts: defaults.MaxRestarts,
		MaxMemory:   defaults.MaxMemory,
		Env:         defaults.Env,
	}
}

// PM2Registration returns saved regular settings, falling back to generated
// defaults when a robot has not been registered yet.
func (m Manager) PM2Registration(root string) (PM2RegistrationSettings, error) {
	path, err := projectPath(root)
	if err != nil {
		return PM2RegistrationSettings{}, err
	}
	settings := defaultPM2RegistrationSettings(path)
	data, err := os.ReadFile(filepath.Join(path, "pm2.config.cjs"))
	if os.IsNotExist(err) {
		return settings, nil
	}
	if err != nil {
		return PM2RegistrationSettings{}, fmt.Errorf("读取 PM2 配置失败：%w", err)
	}
	first, _, _ := strings.Cut(string(data), "\n")
	if !strings.HasPrefix(first, pm2SettingsPrefix) {
		settings.CustomConfig = true
		return settings, nil
	}
	if err := json.Unmarshal([]byte(strings.TrimPrefix(first, pm2SettingsPrefix)), &settings); err != nil {
		return PM2RegistrationSettings{}, errors.New("PM2 常规配置无法识别")
	}
	settings.Registered = true
	return settings, nil
}

// SavePM2Registration writes generated PM2 config from validated regular
// settings. It never accepts raw ecosystem JavaScript from the browser.
func (m Manager) SavePM2Registration(root string, settings PM2RegistrationSettings, overwriteCustom bool) (PM2RegistrationSettings, error) {
	path, err := projectPath(root)
	if err != nil {
		return PM2RegistrationSettings{}, err
	}
	if err := validatePM2RegistrationSettings(&settings); err != nil {
		return PM2RegistrationSettings{}, err
	}
	configPath := filepath.Join(path, "pm2.config.cjs")
	if data, readErr := os.ReadFile(configPath); readErr == nil {
		first, _, _ := strings.Cut(string(data), "\n")
		if !strings.HasPrefix(first, pm2SettingsPrefix) && !overwriteCustom {
			return PM2RegistrationSettings{}, errors.New("检测到自定义 PM2 配置；确认后才会由 AlemonX 接管并覆盖")
		}
	} else if !os.IsNotExist(readErr) {
		return PM2RegistrationSettings{}, fmt.Errorf("读取 PM2 配置失败：%w", readErr)
	}
	if err := pm2config.EnsureID(path); err != nil {
		return PM2RegistrationSettings{}, err
	}
	if err := os.WriteFile(configPath, []byte(pm2config.ConfigWithOptions(path, pm2config.Options{
		Name:        settings.Name,
		Script:      settings.Script,
		Autorestart: settings.Autorestart,
		MaxRestarts: settings.MaxRestarts,
		MaxMemory:   settings.MaxMemory,
		Env:         settings.Env,
	})), 0o644); err != nil {
		return PM2RegistrationSettings{}, fmt.Errorf("保存 PM2 配置失败：%w", err)
	}
	settings.Registered = true
	settings.CustomConfig = false
	return settings, nil
}

// RegisterPM2 saves the regular settings and runs one idempotent
// startOrReload command, so registering and updating are the same simple flow.
func (m Manager) RegisterPM2(root string, settings PM2RegistrationSettings, overwriteCustom bool) (Result, error) {
	settings, err := m.SavePM2Registration(root, settings, overwriteCustom)
	if err != nil {
		return Result{}, err
	}
	dependencyOutput, err := m.EnsureRuntimeDependencies(root)
	if err != nil {
		return Result{Path: root, Output: dependencyOutput}, err
	}
	name, args := pm2Launcher(root)
	output, runErr := run(root, name, append(args, "startOrReload", "pm2.config.cjs", "--update-env")...)
	if runErr != nil {
		return Result{Path: root, Output: strings.TrimSpace(dependencyOutput + "\n" + output)}, runErr
	}
	saveOutput, saveErr := run(root, name, append(args, "save")...)
	if saveErr != nil {
		return Result{Path: root, Output: strings.TrimSpace(dependencyOutput + "\n" + output + "\n" + saveOutput)}, fmt.Errorf("PM2 已注册，但保存重启恢复清单失败：%w", saveErr)
	}
	return Result{Path: root, Output: strings.TrimSpace(dependencyOutput + "\n" + output + "\n" + saveOutput + "\n已注册 " + settings.Name)}, nil
}

func validatePM2RegistrationSettings(settings *PM2RegistrationSettings) error {
	settings.Name = strings.TrimSpace(settings.Name)
	settings.Script = strings.TrimSpace(settings.Script)
	settings.MaxMemory = strings.ToUpper(strings.TrimSpace(settings.MaxMemory))
	if !pm2RegistrationNamePattern.MatchString(settings.Name) {
		return errors.New("进程名称只能包含字母、数字、点、下划线和连字符")
	}
	cleaned := filepath.Clean(filepath.FromSlash(settings.Script))
	if settings.Script == "" || filepath.IsAbs(cleaned) || cleaned == ".." || strings.HasPrefix(cleaned, ".."+string(filepath.Separator)) {
		return errors.New("启动文件必须位于机器人目录内")
	}
	settings.Script = "./" + filepath.ToSlash(strings.TrimPrefix(cleaned, "."+string(filepath.Separator)))
	if settings.MaxRestarts < 0 || settings.MaxRestarts > 1000 {
		return errors.New("最大重启次数应在 0 到 1000 之间")
	}
	if settings.MaxMemory != "" && !pm2MemoryPattern.MatchString(settings.MaxMemory) {
		return errors.New("内存上限格式应为数字加 K、M 或 G，例如 512M")
	}
	if settings.Env == nil {
		settings.Env = map[string]string{}
	}
	for key, value := range settings.Env {
		if !pm2EnvironmentNamePattern.MatchString(key) || len(value) > 4096 {
			return errors.New("环境变量格式无效")
		}
	}
	return nil
}
